apiVersion: apps/v1
kind: Deployment
metadata:
  name: navsvc-deployment
  labels:
    app: navsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navsvc
  template:
    metadata:
      labels:
        app: navsvc
    spec:
      containers:
      - name: navsvc
        image: docker.io/library/navsvc:local
        imagePullPolicy: Never # Should never pull, because it's going to rely on it being loaded in by `kind load docker-image`.
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: navsvc-service
spec:
  selector:
    app: navsvc
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navsvc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /nav/?(.*)
        pathType: Prefix
        backend:
          service:
            name: navsvc-service
            port:
              number: 80